import { Shipment, Driver, ChatThread } from '@/types';

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'drv-001',
    fullName: 'Mehmet Yılmaz',
    username: 'mehmet.yilmaz',
    email: 'mehmet.yilmaz@driver.com',
    phone: '+90 532 111 2233',
    plateNumber: '34 TIR 001',
    truckClass: 'Box Truck',
    emailVerified: true,
    status: 'Active',
    avatarInitials: 'MY',
  },
  {
    id: 'drv-002',
    fullName: 'Hasan Al-Rashid',
    username: 'hasan.rashid',
    email: 'hasan.rashid@driver.com',
    phone: '+964 770 234 5678',
    plateNumber: '18 TIR 047',
    truckClass: 'Refrigerated',
    emailVerified: true,
    status: 'Active',
    avatarInitials: 'HR',
  },
  {
    id: 'drv-003',
    fullName: 'Ahmet Kaya',
    username: 'ahmet.kaya',
    email: 'ahmet.kaya@driver.com',
    phone: '+90 542 987 6543',
    plateNumber: '06 TIR 219',
    truckClass: 'Flatbed',
    emailVerified: true,
    status: 'Idle',
    avatarInitials: 'AK',
  },
  {
    id: 'drv-004',
    fullName: 'Omar Khalid',
    username: 'omar.khalid',
    email: 'omar.khalid@driver.com',
    phone: '+964 750 112 3344',
    plateNumber: '07 TIR 088',
    truckClass: 'Container',
    emailVerified: false,
    status: 'Offline',
    avatarInitials: 'OK',
  },
];

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: 'shp-1001',
    tirNumber: 'TIR-TR2024-44881',
    token: 'token-1001',
    driverId: 'drv-001',
    driverName: 'Mehmet Yılmaz',
    plateNumber: '34 TIR 001',
    origin: 'Istanbul, Turkey',
    destination: 'Baghdad, Iraq',
    cargoDescription: 'Industrial Machinery Parts',
    cargoValue: '$84,500',
    weight: '18,200 kg',
    status: 'Customs Clearance',
    shipmentType: 'Road',
    containers: [],
    estimatedArrival: 'Jun 7, 2026',
    createdAt: 'Jun 3, 2026',
    updatedAt: 'Jun 5, 2026 09:41',
    checkpoints: [
      { id: 'cp-1', name: 'Istanbul Depot', location: 'Istanbul, TR', status: 'Cleared', timestamp: 'Jun 3, 14:00' },
      { id: 'cp-2', name: 'Ankara Hub', location: 'Ankara, TR', status: 'Cleared', timestamp: 'Jun 4, 08:20' },
      { id: 'cp-3', name: 'Habur Border Gate', location: 'Şırnak, TR', status: 'Current', timestamp: 'Jun 5, 09:41' },
      { id: 'cp-4', name: 'Ibrahim Khalil Crossing', location: 'Zakho, IQ', status: 'Upcoming' },
      { id: 'cp-5', name: 'Mosul Inspection', location: 'Mosul, IQ', status: 'Upcoming' },
      { id: 'cp-6', name: 'Baghdad Terminal', location: 'Baghdad, IQ', status: 'Upcoming' },
    ],
  },
  {
    id: 'shp-1002',
    tirNumber: 'TIR-TR2024-44902',
    token: 'token-1002',
    driverId: 'drv-002',
    driverName: 'Hasan Al-Rashid',
    plateNumber: '18 TIR 047',
    origin: 'Mersin, Turkey',
    destination: 'Basra, Iraq',
    cargoDescription: 'Refrigerated Pharmaceuticals',
    cargoValue: '$210,000',
    weight: '9,800 kg',
    status: 'In Transit',
    shipmentType: 'Road',
    containers: [],
    estimatedArrival: 'Jun 8, 2026',
    createdAt: 'Jun 4, 2026',
    updatedAt: 'Jun 5, 2026 07:15',
    checkpoints: [
      { id: 'cp-1', name: 'Mersin Port Depot', location: 'Mersin, TR', status: 'Cleared', timestamp: 'Jun 4, 06:00' },
      { id: 'cp-2', name: 'Gaziantep Hub', location: 'Gaziantep, TR', status: 'Cleared', timestamp: 'Jun 4, 18:30' },
      { id: 'cp-3', name: 'Kilis Border Gate', location: 'Kilis, TR', status: 'Cleared', timestamp: 'Jun 5, 07:15' },
      { id: 'cp-4', name: 'Tall Abyad', location: 'Northern Syria', status: 'Current', timestamp: 'Jun 5, 11:00' },
      { id: 'cp-5', name: 'Basra Checkpoint', location: 'Basra, IQ', status: 'Upcoming' },
    ],
  },
  {
    id: 'shp-1003',
    tirNumber: 'TIR-TR2024-45010',
    token: 'token-1003',
    driverId: 'drv-003',
    driverName: 'Ahmet Kaya',
    plateNumber: '06 TIR 219',
    origin: 'Ankara, Turkey',
    destination: 'Erbil, Iraq',
    cargoDescription: 'Steel Structural Beams',
    cargoValue: '$62,000',
    weight: '24,600 kg',
    status: 'Dispatched',
    shipmentType: 'Road',
    containers: [],
    estimatedArrival: 'Jun 9, 2026',
    createdAt: 'Jun 5, 2026',
    updatedAt: 'Jun 5, 2026 11:00',
    checkpoints: [
      { id: 'cp-1', name: 'Ankara Loading Yard', location: 'Ankara, TR', status: 'Current', timestamp: 'Jun 5, 11:00' },
      { id: 'cp-2', name: 'Diyarbakır Hub', location: 'Diyarbakır, TR', status: 'Upcoming' },
      { id: 'cp-3', name: 'Silopi Border Gate', location: 'Şırnak, TR', status: 'Upcoming' },
      { id: 'cp-4', name: 'Zakho Crossing', location: 'Zakho, IQ', status: 'Upcoming' },
      { id: 'cp-5', name: 'Erbil Terminal', location: 'Erbil, IQ', status: 'Upcoming' },
    ],
  },
  {
    id: 'shp-1004',
    tirNumber: 'TIR-TR2024-44750',
    token: 'token-1004',
    driverId: 'drv-002',
    driverName: 'Hasan Al-Rashid',
    plateNumber: '18 TIR 047',
    origin: 'Izmir, Turkey',
    destination: 'Baghdad, Iraq',
    cargoDescription: 'Consumer Electronics',
    cargoValue: '$320,000',
    weight: '7,400 kg',
    status: 'Arrived',
    shipmentType: 'Road',
    containers: [],
    estimatedArrival: 'Jun 4, 2026',
    createdAt: 'May 31, 2026',
    updatedAt: 'Jun 4, 2026 16:22',
    checkpoints: [
      { id: 'cp-1', name: 'Izmir Port', location: 'Izmir, TR', status: 'Cleared', timestamp: 'Jun 1, 07:00' },
      { id: 'cp-2', name: 'Konya Hub', location: 'Konya, TR', status: 'Cleared', timestamp: 'Jun 2, 09:15' },
      { id: 'cp-3', name: 'Habur Border Gate', location: 'Şırnak, TR', status: 'Cleared', timestamp: 'Jun 3, 12:00' },
      { id: 'cp-4', name: 'Ibrahim Khalil Crossing', location: 'Zakho, IQ', status: 'Cleared', timestamp: 'Jun 3, 18:45' },
      { id: 'cp-5', name: 'Baghdad Terminal', location: 'Baghdad, IQ', status: 'Cleared', timestamp: 'Jun 4, 16:22' },
    ],
  },
];

export const MOCK_CHAT_THREADS: ChatThread[] = [
  {
    id: 'thread-001',
    driverId: 'drv-001',
    driverName: 'Mehmet Yılmaz',
    driverPlate: '34 TIR 001',
    lastMessage: 'Documents requested by customs officer at Habur.',
    lastMessageTime: '09:41',
    unreadCount: 2,
    messages: [
      {
        id: 'msg-1',
        senderId: 'admin-001',
        senderName: 'Dispatch (MARAS)',
        senderRole: 'admin',
        content: 'Good morning Mehmet. Please confirm your ETA at Habur gate.',
        timestamp: '08:15',
        read: true,
      },
      {
        id: 'msg-2',
        senderId: 'drv-001',
        senderName: 'Mehmet Yılmaz',
        senderRole: 'driver',
        content: 'GM. I am 20 minutes away from Habur. Traffic is clear.',
        timestamp: '08:22',
        read: true,
      },
      {
        id: 'msg-3',
        senderId: 'drv-001',
        senderName: 'Mehmet Yılmaz',
        senderRole: 'driver',
        content: 'Documents requested by customs officer at Habur.',
        timestamp: '09:41',
        read: false,
      },
      {
        id: 'msg-4',
        senderId: 'drv-001',
        senderName: 'Mehmet Yılmaz',
        senderRole: 'driver',
        content: 'They want TIR carnet + invoice + packing list. Please advise.',
        timestamp: '09:42',
        read: false,
      },
    ],
  },
  {
    id: 'thread-002',
    driverId: 'drv-002',
    driverName: 'Hasan Al-Rashid',
    driverPlate: '18 TIR 047',
    lastMessage: 'Cargo temperature stable at +4°C. All good.',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-5',
        senderId: 'admin-001',
        senderName: 'Dispatch (MARAS)',
        senderRole: 'admin',
        content: 'Hasan, please confirm cold chain temperature every 4 hours.',
        timestamp: 'Yesterday 14:00',
        read: true,
      },
      {
        id: 'msg-6',
        senderId: 'drv-002',
        senderName: 'Hasan Al-Rashid',
        senderRole: 'driver',
        content: 'Cargo temperature stable at +4°C. All good.',
        timestamp: 'Yesterday 18:00',
        read: true,
      },
    ],
  },
  {
    id: 'thread-003',
    driverId: 'drv-003',
    driverName: 'Ahmet Kaya',
    driverPlate: '06 TIR 219',
    lastMessage: 'Loaded and ready to depart.',
    lastMessageTime: '11:00',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-7',
        senderId: 'drv-003',
        senderName: 'Ahmet Kaya',
        senderRole: 'driver',
        content: 'Loaded and ready to depart.',
        timestamp: '11:00',
        read: true,
      },
    ],
  },
];

// Hardcoded credentials removed — use real Supabase authentication.
